language: node_js
node_js:
  - "lts/*"
  - "node"
os:
  - linux
  - osx
  - windows
script:
  - npm run build
  - npm install -g codecov
  - npm run test:cov
  - codecov
matrix:
  allow_failures:
    - node_js:  "node"
